# Managed by 1Password (WP-P4-SECRETS-001). Load with: op run --env-file=.env.op.tpl -- <cmd>
# Real secrets live in the 'LyfeOS' 1Password vault. NO plaintext values here.
DATABASE_URL=op://LyfeOS/Development/DATABASE_URL
SESSION_SECRET=op://LyfeOS/Development/SESSION_SECRET
AI_INTEGRATIONS_ANTHROPIC_BASE_URL=op://LyfeOS/Development/AI_INTEGRATIONS_ANTHROPIC_BASE_URL
AI_INTEGRATIONS_ANTHROPIC_API_KEY=op://LyfeOS/Development/AI_INTEGRATIONS_ANTHROPIC_API_KEY
GOOGLE_OAUTH_CLIENT_ID=op://LyfeOS/Development/GOOGLE_OAUTH_CLIENT_ID
GOOGLE_OAUTH_CLIENT_SECRET=op://LyfeOS/Development/GOOGLE_OAUTH_CLIENT_SECRET
GOOGLE_OAUTH_REDIRECT_URI=https://lyfeos.net/api/google/callback
VITE_CLERK_PUBLISHABLE_KEY=op://LyfeOS/Development/CLERK_PUBLISHABLE_KEY
CLERK_SECRET_KEY=op://LyfeOS/Development/CLERK_SECRET_KEY
CLERK_WEBHOOK_SIGNING_SECRET=op://LyfeOS/Development/CLERK_WEBHOOK_SIGNING_SECRET
