import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Archive, FolderKanban, Link2, Plus, Save, Unlink } from "lucide-react";
import { projectStates, projectStateSchema } from "@shared/projects";
import type { z } from "zod";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { usePageTitle } from "@/hooks/use-page-title";
import { useToast } from "@/hooks/use-toast";

type ProjectState = z.infer<typeof projectStateSchema>;
type Project = { id: number; title: string; description: string | null; outcome: string | null; state: ProjectState; startDate: string | null; dueDate: string | null; revision: number; taskCount?: number; completedTaskCount?: number; updatedAt: string };
type Mission = { id: number; title: string; description: string; completed: boolean; projectId: number | null; dueDate: string | null };
type ProjectEvent = { id: number; eventType: string; fromState: string | null; toState: string | null; occurredAt: string };
const labels: Record<ProjectState, string> = { planned: "Planned", active: "Active", on_hold: "On hold", completed: "Completed", archived: "Archived" };

export default function ProjectsPage() {
  usePageTitle("Projects");
  const { toast } = useToast();
  const [selectedId, setSelectedId] = useState<number | null>(() => { const id = Number(new URLSearchParams(window.location.search).get("project")); return Number.isInteger(id) && id > 0 ? id : null; });
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [outcome, setOutcome] = useState(""); const [startDate, setStartDate] = useState(""); const [dueDate, setDueDate] = useState("");
  const [newTitle, setNewTitle] = useState(""); const [newOutcome, setNewOutcome] = useState(""); const [missionTitle, setMissionTitle] = useState(""); const [linkMissionId, setLinkMissionId] = useState<number | null>(null); const [nextState, setNextState] = useState<ProjectState>("planned");
  const list = useQuery<{ projects: Project[] }>({ queryKey: ["/api/projects"], queryFn: () => apiRequest("/api/projects") });
  const detail = useQuery<{ project: Project; missions: Mission[]; history: ProjectEvent[] }>({ queryKey: ["/api/projects", selectedId], queryFn: () => apiRequest(`/api/projects/${selectedId}`), enabled: selectedId !== null });
  const missionOptions = useQuery<{ missions: Mission[] }>({ queryKey: ["/api/automations/missions"], queryFn: () => apiRequest("/api/automations/missions") });
  useEffect(() => { if (!selectedId && list.data?.projects[0]) setSelectedId(list.data.projects[0].id); }, [list.data, selectedId]);
  useEffect(() => { const p = detail.data?.project; if (!p) return; setTitle(p.title); setDescription(p.description || ""); setOutcome(p.outcome || ""); setStartDate(p.startDate || ""); setDueDate(p.dueDate || ""); setNextState(p.state); }, [detail.data]);
  const refresh = async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["/api/projects"] }), selectedId ? queryClient.invalidateQueries({ queryKey: ["/api/projects", selectedId] }) : Promise.resolve(), queryClient.invalidateQueries({ queryKey: ["/api/automations/missions"] })]); };
  const create = useMutation({ mutationFn: () => apiRequest<{ project: Project }>("/api/projects", { method: "POST", body: JSON.stringify({ title: newTitle, outcome: newOutcome, description: null, startDate: null, dueDate: null }) }), onSuccess: async ({ project }) => { setNewTitle(""); setNewOutcome(""); await queryClient.invalidateQueries({ queryKey: ["/api/projects"] }); setSelectedId(project.id); toast({ title: "Project created" }); } });
  const save = useMutation({ mutationFn: () => apiRequest(`/api/projects/${selectedId}`, { method: "PATCH", body: JSON.stringify({ title, description: description || null, outcome, startDate: startDate || null, dueDate: dueDate || null, expectedRevision: detail.data!.project.revision }) }), onSuccess: async () => { await refresh(); toast({ title: "Project saved" }); } });
  const transition = useMutation({ mutationFn: () => apiRequest(`/api/projects/${selectedId}/state`, { method: "POST", body: JSON.stringify({ state: nextState, expectedRevision: detail.data!.project.revision }) }), onSuccess: async () => { await refresh(); toast({ title: "Project state updated" }); }, onError: (error) => toast({ title: "State was not changed", description: error instanceof Error ? error.message : "Please try again.", variant: "destructive" }) });
  const createMission = useMutation({ mutationFn: () => apiRequest(`/api/projects/${selectedId}/missions/new`, { method: "POST", body: JSON.stringify({ title: missionTitle, description: "", dueDate: null }) }), onSuccess: async () => { setMissionTitle(""); await refresh(); toast({ title: "Mission added to project" }); } });
  const linkMission = useMutation({ mutationFn: () => apiRequest(`/api/projects/${selectedId}/missions`, { method: "POST", body: JSON.stringify({ missionId: linkMissionId, expectedRevision: detail.data!.project.revision }) }), onSuccess: async () => { setLinkMissionId(null); await refresh(); toast({ title: "Mission linked" }); } });
  const unlinkMission = useMutation({ mutationFn: (missionId: number) => apiRequest(`/api/projects/${selectedId}/missions/${missionId}`, { method: "DELETE" }), onSuccess: refresh });
  const project = detail.data?.project; const available = missionOptions.data?.missions.filter((mission) => !mission.projectId) || [];
  return <div className="container max-w-6xl space-y-5 py-6">
    <div><p className="text-xs font-mono uppercase tracking-[0.14em] text-primary">Outcomes coordinated through Missions</p><h1 className="font-orbitron text-2xl">Projects</h1><p className="text-sm text-muted-foreground">Projects group work toward a declared outcome. Missions remain the only task, completion, and activity-XP authority.</p></div>
    <section className="grid gap-2 rounded-xl border border-primary/15 bg-card/35 p-4 md:grid-cols-[1fr_1fr_auto]"><Input aria-label="New project title" placeholder="Project title" value={newTitle} onChange={(event) => setNewTitle(event.target.value)} /><Input aria-label="New project outcome" placeholder="Done when…" value={newOutcome} onChange={(event) => setNewOutcome(event.target.value)} /><Button disabled={!newTitle.trim() || !newOutcome.trim() || create.isPending} onClick={() => create.mutate()}><Plus className="mr-1 h-4 w-4" />Create</Button></section>
    <div className="grid gap-5 lg:grid-cols-[280px_1fr]"><aside className="space-y-2 rounded-xl border border-primary/15 bg-card/35 p-3">{list.data?.projects.length ? list.data.projects.map((item) => <button key={item.id} className={`w-full rounded-lg border p-3 text-left ${selectedId === item.id ? "border-primary/45 bg-primary/10" : "border-transparent hover:bg-primary/5"}`} onClick={() => setSelectedId(item.id)}><span className="flex items-center gap-2"><FolderKanban className="h-4 w-4 text-primary" /><strong className="truncate text-sm">{item.title}</strong></span><span className="mt-1 block text-xs text-muted-foreground">{labels[item.state]} · {item.completedTaskCount || 0}/{item.taskCount || 0} missions</span></button>) : <p className="p-5 text-center text-sm text-muted-foreground">No projects yet.</p>}</aside>
      {project ? <main className="space-y-5"><section className="space-y-4 rounded-xl border border-primary/15 bg-card/35 p-5"><div className="flex flex-wrap items-center justify-between gap-2"><strong>Project contract</strong><Button onClick={() => save.mutate()} disabled={!title.trim() || !outcome.trim() || save.isPending}><Save className="mr-1 h-4 w-4" />Save</Button></div><div className="grid gap-3 md:grid-cols-2"><label className="space-y-1 text-xs text-muted-foreground">Title<Input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="space-y-1 text-xs text-muted-foreground">Outcome<Input value={outcome} onChange={(event) => setOutcome(event.target.value)} /></label><label className="space-y-1 text-xs text-muted-foreground md:col-span-2">Description<Textarea value={description} onChange={(event) => setDescription(event.target.value)} /></label><label className="space-y-1 text-xs text-muted-foreground">Start date<Input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label className="space-y-1 text-xs text-muted-foreground">Due date<Input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} /></label></div><div className="flex flex-wrap gap-2"><select aria-label="Project state" className="h-9 rounded-md border border-input bg-background px-3 text-sm" value={nextState} onChange={(event) => setNextState(event.target.value as ProjectState)}>{projectStates.map((state) => <option key={state} value={state}>{labels[state]}</option>)}</select><Button variant="outline" disabled={nextState === project.state || transition.isPending} onClick={() => transition.mutate()}>{nextState === "archived" ? <Archive className="mr-1 h-4 w-4" /> : null}Change state</Button><span className="self-center text-xs text-muted-foreground">Revision {project.revision}. Completion requires no open linked Missions.</span></div></section>
      <section className="space-y-4 rounded-xl border border-primary/15 bg-card/35 p-5"><div><strong>Project Missions</strong><p className="text-xs text-muted-foreground">Creating or linking here does not create a second task record.</p></div><div className="flex gap-2"><Input placeholder="New mission title" value={missionTitle} onChange={(event) => setMissionTitle(event.target.value)} /><Button disabled={!missionTitle.trim() || createMission.isPending} onClick={() => createMission.mutate()}><Plus className="mr-1 h-4 w-4" />Mission</Button></div><div className="flex gap-2"><select aria-label="Link existing mission" className="h-9 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm" value={linkMissionId || ""} onChange={(event) => setLinkMissionId(Number(event.target.value))}><option value="">Link an existing unassigned mission</option>{available.map((mission) => <option key={mission.id} value={mission.id}>{mission.title}</option>)}</select><Button variant="outline" disabled={!linkMissionId || linkMission.isPending} onClick={() => linkMission.mutate()}><Link2 className="mr-1 h-4 w-4" />Link</Button></div>{detail.data?.missions.length ? <div className="divide-y divide-primary/10">{detail.data.missions.map((mission) => <div key={mission.id} className="flex items-center justify-between gap-2 py-3 text-sm"><span className={mission.completed ? "text-muted-foreground line-through" : ""}>{mission.completed ? "✓ " : ""}{mission.title}</span><Button size="icon" variant="ghost" aria-label="Unlink mission" onClick={() => unlinkMission.mutate(mission.id)}><Unlink className="h-4 w-4" /></Button></div>)}</div> : <p className="text-sm text-muted-foreground">No Missions linked yet.</p>}</section>
      <section className="rounded-xl border border-primary/15 bg-card/35 p-5"><strong>Project history</strong>{detail.data?.history.length ? <div className="mt-2 divide-y divide-primary/10">{detail.data.history.map((event) => <div key={event.id} className="flex justify-between gap-2 py-2 text-xs"><span>{event.eventType}</span><span className="text-muted-foreground">{new Date(event.occurredAt).toLocaleString()}</span></div>)}</div> : <p className="mt-2 text-sm text-muted-foreground">No history yet.</p>}</section></main> : <div className="rounded-xl border border-dashed border-primary/20 p-10 text-center text-sm text-muted-foreground">Create a Project to coordinate related Missions.</div>}</div>
  </div>;
}
