import { useEffect, useState } from "react";
import { Link, useLocation, useParams } from "wouter";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ClipboardList, Plus, Save, Trash2 } from "lucide-react";
import { createWorkspaceColumn, type WorkspaceColumn, type WorkspaceDatabaseDefinition, type WorkspaceRowValues } from "@shared/tables";
import { WorkspaceFieldInput } from "@/components/tables/WorkspaceFieldInput";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { usePageTitle } from "@/hooks/use-page-title";

type RecordData = { id: number; title: string; description: string | null; category: string; definition: WorkspaceDatabaseDefinition };
type Row = { id: number; values: WorkspaceRowValues; updatedAt: string };
type Form = { id: number; title: string; active: boolean };
type Response = { database: RecordData; rows: Row[]; forms: Form[] };

export default function TableEditorPage() {
  const { databaseId } = useParams(); const id = Number(databaseId); const [, navigate] = useLocation(); const { toast } = useToast();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [category, setCategory] = useState("general");
  const [definition, setDefinition] = useState<WorkspaceDatabaseDefinition>({ version: 1, columns: [] }); const [values, setValues] = useState<WorkspaceRowValues>({}); const [dirty, setDirty] = useState(false);
  const query = useQuery<Response>({ queryKey: ["/api/databases", id], queryFn: () => apiRequest(`/api/databases/${id}`), enabled: Number.isInteger(id) });
  useEffect(() => { if (!query.data) return; setTitle(query.data.database.title); setDescription(query.data.database.description || ""); setCategory(query.data.database.category); setDefinition(query.data.database.definition); setDirty(false); }, [query.data?.database.id]);
  usePageTitle(title || "Table");
  const refresh = () => queryClient.invalidateQueries({ queryKey: ["/api/databases", id] });
  const save = useMutation({ mutationFn: () => apiRequest(`/api/databases/${id}`, { method: "PATCH", body: JSON.stringify({ title, description: description || null, category, definition }) }), onSuccess: () => { setDirty(false); refresh(); toast({ title: "Table saved" }); }, onError: (error) => toast({ title: "Table could not be saved", description: error instanceof Error ? error.message : "Invalid definition", variant: "destructive" }) });
  const addRow = useMutation({ mutationFn: () => apiRequest(`/api/databases/${id}/rows`, { method: "POST", body: JSON.stringify({ values }) }), onSuccess: () => { setValues({}); refresh(); toast({ title: "Row added" }); }, onError: (error) => toast({ title: "Row rejected", description: error instanceof Error ? error.message : "Check the values", variant: "destructive" }) });
  const removeRow = useMutation({ mutationFn: (rowId: number) => apiRequest(`/api/databases/${id}/rows/${rowId}`, { method: "DELETE" }), onSuccess: refresh });
  const createForm = useMutation({ mutationFn: () => apiRequest<{ form: Form }>("/api/forms", { method: "POST", body: JSON.stringify({ databaseId: id, title: `${title} Form`, description: description || null, fieldIds: definition.columns.map((column) => column.id), confirmationText: "Response saved.", active: true }) }), onSuccess: ({ form }) => { refresh(); navigate(`/forms/${form.id}`); } });
  const updateColumn = (columnId: string, changes: Partial<WorkspaceColumn>) => { setDefinition((current) => ({ ...current, columns: current.columns.map((column) => column.id === columnId ? { ...column, ...changes } : column) })); setDirty(true); };
  if (query.isLoading) return <div className="container py-8 text-sm text-muted-foreground">Loading table…</div>; if (!query.data) return <div className="container py-8 text-sm text-destructive">Table unavailable.</div>;
  return <div className="container max-w-[1500px] py-5 space-y-5">
    <div className="flex flex-wrap items-center gap-2"><Link href="/databases"><Button variant="outline">Tables</Button></Link><Input aria-label="Table title" value={title} onChange={(e) => { setTitle(e.target.value); setDirty(true); }} className="max-w-md" /><Button className="ml-auto" disabled={!dirty || !title.trim() || save.isPending} onClick={() => save.mutate()}><Save className="mr-1 h-4 w-4" />Save</Button></div>
    <div className="grid gap-2 md:grid-cols-[180px_1fr]"><Input aria-label="Table category" value={category} onChange={(e) => { setCategory(e.target.value); setDirty(true); }} /><Textarea aria-label="Table description" value={description} onChange={(e) => { setDescription(e.target.value); setDirty(true); }} className="min-h-9 py-2" /></div>
    <section className="rounded-xl border border-primary/15 bg-card/30 p-4 space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-medium">Columns</h2><p className="text-xs text-muted-foreground">Changing a definition is blocked if it would invalidate saved rows or forms.</p></div><Button size="sm" variant="outline" onClick={() => { setDefinition((current) => ({ ...current, columns: [...current.columns, createWorkspaceColumn()] })); setDirty(true); }}><Plus className="mr-1 h-4 w-4" />Column</Button></div>{definition.columns.map((column) => <div key={column.id} className="grid gap-2 rounded border border-primary/10 p-2 md:grid-cols-[1fr_130px_100px_1.2fr_36px]"><Input aria-label="Column name" value={column.name} onChange={(e) => updateColumn(column.id, { name: e.target.value })} /><select aria-label={`${column.name} type`} value={column.type} onChange={(e) => updateColumn(column.id, { type: e.target.value as WorkspaceColumn["type"], options: e.target.value === "select" ? (column.options.length ? column.options : ["Option 1"]) : [] })} className="h-9 rounded-md border border-primary/20 bg-background px-2 text-sm">{["text", "number", "boolean", "date", "select", "url"].map((type) => <option key={type}>{type}</option>)}</select><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={column.required} onChange={(e) => updateColumn(column.id, { required: e.target.checked })} />Required</label><Input aria-label={`${column.name} options`} disabled={column.type !== "select"} value={column.options.join(", ")} onChange={(e) => updateColumn(column.id, { options: e.target.value.split(",").map((item) => item.trim()).filter(Boolean) })} placeholder="Options, comma separated" /><Button size="icon" variant="ghost" disabled={definition.columns.length === 1} onClick={() => { setDefinition((current) => ({ ...current, columns: current.columns.filter((item) => item.id !== column.id) })); setDirty(true); }}><Trash2 className="h-4 w-4" /></Button></div>)}</section>
    <section className="rounded-xl border border-primary/15 bg-card/30 p-4 space-y-3"><div className="flex items-center justify-between"><div><h2 className="font-medium">Forms</h2><p className="text-xs text-muted-foreground">Forms submit validated rows into this table.</p></div><Button size="sm" variant="outline" disabled={dirty || createForm.isPending} onClick={() => createForm.mutate()}><ClipboardList className="mr-1 h-4 w-4" />New form</Button></div><div className="flex flex-wrap gap-2">{query.data.forms.map((form) => <Button key={form.id} variant="outline" onClick={() => navigate(`/forms/${form.id}`)}>{form.title}{!form.active ? " (closed)" : ""}</Button>)}{!query.data.forms.length && <p className="text-xs text-muted-foreground">Save the table definition, then create a form.</p>}</div></section>
    <section className="space-y-3"><h2 className="font-medium">Add row</h2><div className="grid gap-2 md:grid-cols-2 lg:grid-cols-3">{definition.columns.map((column) => <label key={column.id} className="space-y-1 text-xs text-muted-foreground"><span>{column.name}{column.required ? " *" : ""}</span><WorkspaceFieldInput column={column} values={values} onChange={(value) => setValues((current) => ({ ...current, [column.id]: value }))} /></label>)}</div><Button disabled={dirty || addRow.isPending} onClick={() => addRow.mutate()}><Plus className="mr-1 h-4 w-4" />Add row</Button></section>
    <div className="overflow-x-auto rounded-xl border border-primary/15"><table className="w-full min-w-[700px] text-sm"><thead className="bg-card/70"><tr>{definition.columns.map((column) => <th key={column.id} className="px-3 py-2 text-left font-medium">{column.name}</th>)}<th className="w-12" /></tr></thead><tbody>{query.data.rows.map((row) => <tr key={row.id} className="border-t border-primary/10">{definition.columns.map((column) => <td key={column.id} className="max-w-xs truncate px-3 py-2 text-muted-foreground">{typeof row.values[column.id] === "boolean" ? (row.values[column.id] ? "Yes" : "No") : String(row.values[column.id] ?? "")}</td>)}<td><Button size="icon" variant="ghost" onClick={() => removeRow.mutate(row.id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}{!query.data.rows.length && <tr><td colSpan={definition.columns.length + 1} className="p-8 text-center text-muted-foreground">No rows yet.</td></tr>}</tbody></table></div>
  </div>;
}
