import { useEffect, useState } from "react";
import { Link } from "wouter";
import { ArchiveRestore, ExternalLink, Star, Trash2 } from "lucide-react";
import { DataVaultSuiteNavigation } from "@/components/data-vault/DataVaultSuiteNavigation";

type VaultItem = { id: number; type: string; title: string; description?: string | null; href: string; favorite: boolean; trashedAt?: string | null; updatedAt: string };
export default function VaultWorkspacePage() {
  const [view, setView] = useState<"recent" | "favorites" | "trash">("recent");
  const [items, setItems] = useState<VaultItem[]>([]); const [loading, setLoading] = useState(true);
  const load = async (next = view) => { setLoading(true); const response = await fetch(`/api/vault/items?view=${next}`, { credentials: "include" }); const data = await response.json(); setItems(data.items ?? []); setLoading(false); };
  useEffect(() => { void load(view); }, [view]);
  const act = async (item: VaultItem, action: string) => { await fetch(`/api/vault/items/${item.type}/${item.id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); await load(); };
  return <main className="mx-auto max-w-6xl space-y-6 px-4 py-6"><DataVaultSuiteNavigation active="vault" /><section className="rounded-xl border border-primary/15 bg-card/40 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-orbitron text-lg">Workspace status</p><p className="text-sm text-muted-foreground">One private layer for work you opened, favorited, or moved to Trash.</p></div><div className="flex gap-2">{(["recent", "favorites", "trash"] as const).map((tab) => <button key={tab} onClick={() => setView(tab)} className={`rounded-md px-3 py-2 text-sm capitalize ${view === tab ? "bg-primary text-primary-foreground" : "border border-border text-muted-foreground"}`}>{tab}</button>)}</div></div></section><section className="space-y-3">{loading ? <p className="text-sm text-muted-foreground">Loading workspace…</p> : items.length === 0 ? <p className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">Nothing here yet.</p> : items.map((item) => <article key={`${item.type}-${item.id}`} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-card/45 p-4"><div><p className="text-xs font-mono uppercase tracking-wider text-primary">{item.type}</p><p className="font-medium">{item.title}</p>{item.description && <p className="mt-1 text-sm text-muted-foreground">{item.description}</p>}</div><div className="flex items-center gap-2">{view !== "trash" && <button aria-label="Toggle favorite" onClick={() => act(item, "favorite")} className={`rounded-md p-2 ${item.favorite ? "text-primary" : "text-muted-foreground"}`}><Star className="h-4 w-4" fill={item.favorite ? "currentColor" : "none"} /></button>}{view === "trash" ? <><button onClick={() => act(item, "restore")} className="inline-flex items-center gap-1 rounded-md border px-2 py-1 text-sm"><ArchiveRestore className="h-4 w-4" />Restore</button><button onClick={() => { if (window.confirm(`Delete ${item.title} forever?`)) void act(item, "delete"); }} className="rounded-md p-2 text-destructive" aria-label="Delete forever"><Trash2 className="h-4 w-4" /></button></> : <button onClick={() => act(item, "trash")} className="rounded-md p-2 text-muted-foreground hover:text-destructive" aria-label="Move to trash"><Trash2 className="h-4 w-4" /></button>}<Link href={item.href} onClick={() => void act(item, "open")} className="rounded-md border p-2" aria-label={`Open ${item.title}`}><ExternalLink className="h-4 w-4" /></Link></div></article>)}</section></main>;
}
