import type { Express, Request, Response } from "express";
import { and, desc, eq, isNull } from "drizzle-orm";
import { z } from "zod";
import { db } from "../db";
import { isAuthenticated } from "./middleware";
import { canvases, documents, folders, slideRevisions, slides, spreadsheets, vaultForms, vaultFormResponses, vaultItemStates, workspaceDatabases } from "@shared/schema";

const slideDocumentSchema = z.object({
  version: z.literal(1),
  theme: z.enum(["midnight", "light", "warm"]).default("midnight"),
  slides: z.array(z.object({ id: z.string().min(1).max(100), layout: z.enum(["title", "title_body", "section", "quote"]), title: z.string().max(160), body: z.string().max(6000).default(""), speakerNotes: z.string().max(6000).default(""), accent: z.string().regex(/^#[0-9a-fA-F]{6}$/).default("#00e0ff") })).min(1).max(100),
});
const deckInputSchema = z.object({ title: z.string().trim().min(1).max(180), description: z.string().trim().max(1000).nullable().optional(), document: slideDocumentSchema, expectedRevision: z.number().int().positive().optional() });
const formFieldSchema = z.object({ id: z.string().min(1).max(80), label: z.string().trim().min(1).max(180), type: z.enum(["short_text", "long_text", "email", "number", "date", "select", "checkbox"]), required: z.boolean().default(false), options: z.array(z.string().trim().min(1).max(120)).max(30).default([]) }).superRefine((field, ctx) => { if (field.type === "select" && field.options.length === 0) ctx.addIssue({ code: z.ZodIssueCode.custom, message: "Select fields need at least one option." }); });
const formInputSchema = z.object({ title: z.string().trim().min(1).max(180), description: z.string().trim().max(1000).nullable().optional(), fields: z.array(formFieldSchema).min(1).max(80), confirmationText: z.string().trim().min(1).max(600).default("Response saved."), backingDatabaseId: z.number().int().positive().nullable().optional(), active: z.boolean().optional() });
const stateInputSchema = z.object({ action: z.enum(["favorite", "trash", "restore", "open", "delete"]) });
const responseInputSchema = z.object({ values: z.record(z.string(), z.union([z.string().max(6000), z.number(), z.boolean(), z.null()])) });
const itemTypeSchema = z.enum(["document", "folder", "sheet", "canvas", "slide", "form", "table"]);

function privateResponse(res: Response) { res.setHeader("Cache-Control", "private, no-store, max-age=0"); res.setHeader("Pragma", "no-cache"); res.setHeader("Vary", "Cookie"); }
function parseId(value: string) { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : null; }
function defaultSlideDocument() { return { version: 1 as const, theme: "midnight" as const, slides: [{ id: crypto.randomUUID(), layout: "title" as const, title: "Untitled presentation", body: "", speakerNotes: "", accent: "#00e0ff" }] }; }

async function ownsItem(userId: number, type: z.infer<typeof itemTypeSchema>, id: number) {
  const source = type === "document" ? documents : type === "folder" ? folders : type === "sheet" ? spreadsheets : type === "canvas" ? canvases : type === "slide" ? slides : type === "form" ? vaultForms : workspaceDatabases;
  const [row] = await db.select({ id: source.id }).from(source).where(and(eq(source.id, id), eq(source.userId, userId))).limit(1);
  return Boolean(row);
}
async function permanentlyDeleteItem(userId: number, type: z.infer<typeof itemTypeSchema>, id: number) {
  if (type === "document") await db.delete(documents).where(and(eq(documents.id, id), eq(documents.userId, userId)));
  else if (type === "folder") await db.delete(folders).where(and(eq(folders.id, id), eq(folders.userId, userId)));
  else if (type === "sheet") await db.delete(spreadsheets).where(and(eq(spreadsheets.id, id), eq(spreadsheets.userId, userId)));
  else if (type === "canvas") await db.delete(canvases).where(and(eq(canvases.id, id), eq(canvases.userId, userId)));
  else if (type === "slide") await db.delete(slides).where(and(eq(slides.id, id), eq(slides.userId, userId)));
  else if (type === "form") await db.delete(vaultForms).where(and(eq(vaultForms.id, id), eq(vaultForms.userId, userId)));
  else await db.delete(workspaceDatabases).where(and(eq(workspaceDatabases.id, id), eq(workspaceDatabases.userId, userId)));
  await db.delete(vaultItemStates).where(and(eq(vaultItemStates.userId, userId), eq(vaultItemStates.itemType, type), eq(vaultItemStates.itemId, id)));
}

async function upsertState(userId: number, itemType: z.infer<typeof itemTypeSchema>, itemId: number, patch: Partial<{ favorite: boolean; trashedAt: Date | null; lastOpenedAt: Date }>) {
  const [existing] = await db.select().from(vaultItemStates).where(and(eq(vaultItemStates.userId, userId), eq(vaultItemStates.itemType, itemType), eq(vaultItemStates.itemId, itemId))).limit(1);
  if (existing) return (await db.update(vaultItemStates).set({ ...patch, updatedAt: new Date() }).where(eq(vaultItemStates.id, existing.id)).returning())[0];
  return (await db.insert(vaultItemStates).values({ userId, itemType, itemId, favorite: patch.favorite ?? false, trashedAt: patch.trashedAt ?? null, lastOpenedAt: patch.lastOpenedAt ?? null }).returning())[0];
}

export function registerDataVaultRoutes(app: Express): void {
  app.use("/api/slides", (_req, res, next) => { privateResponse(res); next(); });
  app.use("/api/vault-forms", (_req, res, next) => { privateResponse(res); next(); });
  app.use("/api/vault", (_req, res, next) => { privateResponse(res); next(); });

  app.get("/api/slides", isAuthenticated, async (req, res) => { const rows = await db.select().from(slides).where(and(eq(slides.userId, req.session.userId!), isNull(slides.deletedAt))).orderBy(desc(slides.updatedAt)); res.json({ slides: rows }); });
  app.post("/api/slides", isAuthenticated, async (req, res) => { try { const input = deckInputSchema.parse(req.body); const deck = await db.transaction(async (tx) => { const [created] = await tx.insert(slides).values({ userId: req.session.userId!, title: input.title, description: input.description ?? null, document: input.document }).returning(); await tx.insert(slideRevisions).values({ userId: req.session.userId!, slideId: created.id, revisionNumber: 1, action: "created", snapshot: { title: created.title, description: created.description, document: created.document } }); return created; }); res.status(201).json({ slide: deck }); } catch (error) { res.status(400).json({ error: error instanceof z.ZodError ? error.flatten() : "Invalid presentation." }); } });
  app.get("/api/slides/:id", isAuthenticated, async (req, res) => { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: "Invalid slide id." }); const [deck] = await db.select().from(slides).where(and(eq(slides.id, id), eq(slides.userId, req.session.userId!))).limit(1); if (!deck) return res.status(404).json({ error: "Presentation not found." }); res.json({ slide: deck }); });
  app.patch("/api/slides/:id", isAuthenticated, async (req, res) => { try { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: "Invalid slide id." }); const input = deckInputSchema.parse(req.body); const [current] = await db.select().from(slides).where(and(eq(slides.id, id), eq(slides.userId, req.session.userId!))).limit(1); if (!current) return res.status(404).json({ error: "Presentation not found." }); if (input.expectedRevision && input.expectedRevision !== current.revision) return res.status(409).json({ error: "This presentation changed elsewhere. Refresh before saving.", slide: current }); const deck = await db.transaction(async (tx) => { const [updated] = await tx.update(slides).set({ title: input.title, description: input.description ?? null, document: input.document, revision: current.revision + 1, updatedAt: new Date() }).where(eq(slides.id, id)).returning(); await tx.insert(slideRevisions).values({ userId: req.session.userId!, slideId: id, revisionNumber: updated.revision, action: "updated", snapshot: { title: updated.title, description: updated.description, document: updated.document } }); return updated; }); res.json({ slide: deck }); } catch (error) { res.status(400).json({ error: error instanceof z.ZodError ? error.flatten() : "Invalid presentation." }); } });

  app.get("/api/vault-forms", isAuthenticated, async (req, res) => { const rows = await db.select().from(vaultForms).where(and(eq(vaultForms.userId, req.session.userId!), isNull(vaultForms.deletedAt))).orderBy(desc(vaultForms.updatedAt)); res.json({ forms: rows }); });
  app.post("/api/vault-forms", isAuthenticated, async (req, res) => { try { const input = formInputSchema.parse(req.body); if (input.backingDatabaseId) { const [database] = await db.select({ id: workspaceDatabases.id }).from(workspaceDatabases).where(and(eq(workspaceDatabases.id, input.backingDatabaseId), eq(workspaceDatabases.userId, req.session.userId!))).limit(1); if (!database) return res.status(404).json({ error: "Backing table not found." }); } const [form] = await db.insert(vaultForms).values({ userId: req.session.userId!, title: input.title, description: input.description ?? null, definition: { version: 1, fields: input.fields }, confirmationText: input.confirmationText, backingDatabaseId: input.backingDatabaseId ?? null, active: input.active ?? true }).returning(); res.status(201).json({ form }); } catch (error) { res.status(400).json({ error: error instanceof z.ZodError ? error.flatten() : "Invalid form." }); } });
  app.get("/api/vault-forms/:id", isAuthenticated, async (req, res) => { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: "Invalid form id." }); const [form] = await db.select().from(vaultForms).where(and(eq(vaultForms.id, id), eq(vaultForms.userId, req.session.userId!))).limit(1); if (!form) return res.status(404).json({ error: "Form not found." }); const responses = await db.select().from(vaultFormResponses).where(and(eq(vaultFormResponses.formId, id), eq(vaultFormResponses.userId, req.session.userId!))).orderBy(desc(vaultFormResponses.createdAt)); res.json({ form, responses }); });
  app.patch("/api/vault-forms/:id", isAuthenticated, async (req, res) => { try { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: "Invalid form id." }); const input = formInputSchema.parse(req.body); const [form] = await db.update(vaultForms).set({ title: input.title, description: input.description ?? null, definition: { version: 1, fields: input.fields }, confirmationText: input.confirmationText, backingDatabaseId: input.backingDatabaseId ?? null, active: input.active ?? true, updatedAt: new Date() }).where(and(eq(vaultForms.id, id), eq(vaultForms.userId, req.session.userId!))).returning(); if (!form) return res.status(404).json({ error: "Form not found." }); res.json({ form }); } catch (error) { res.status(400).json({ error: error instanceof z.ZodError ? error.flatten() : "Invalid form." }); } });
  app.post("/api/vault-forms/:id/responses", isAuthenticated, async (req, res) => { try { const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: "Invalid form id." }); const input = responseInputSchema.parse(req.body); const [form] = await db.select().from(vaultForms).where(and(eq(vaultForms.id, id), eq(vaultForms.userId, req.session.userId!), isNull(vaultForms.deletedAt))).limit(1); if (!form) return res.status(404).json({ error: "Form not found." }); const fields = (form.definition as { fields?: Array<{ id: string; type: string; required: boolean; options?: string[] }> }).fields ?? []; for (const field of fields) { const value = input.values[field.id]; if (field.required && (value === undefined || value === null || value === "")) return res.status(400).json({ error: `${field.id} is required.` }); if (value !== undefined && field.type === "email" && typeof value === "string" && !z.string().email().safeParse(value).success) return res.status(400).json({ error: `${field.id} must be an email.` }); if (value !== undefined && field.type === "select" && typeof value === "string" && !field.options?.includes(value)) return res.status(400).json({ error: `${field.id} is not a valid option.` }); } const [response] = await db.insert(vaultFormResponses).values({ userId: req.session.userId!, formId: id, values: input.values }).returning(); res.status(201).json({ response, confirmationText: form.confirmationText }); } catch (error) { res.status(400).json({ error: error instanceof z.ZodError ? error.flatten() : "Invalid response." }); } });

  app.get("/api/vault/items", isAuthenticated, async (req, res) => {
    const userId = req.session.userId!;
    const [docRows, folderRows, sheetRows, canvasRows, slideRows, formRows, tableRows, states] = await Promise.all([
      db.select().from(documents).where(eq(documents.userId, userId)), db.select().from(folders).where(eq(folders.userId, userId)), db.select().from(spreadsheets).where(eq(spreadsheets.userId, userId)), db.select().from(canvases).where(eq(canvases.userId, userId)), db.select().from(slides).where(eq(slides.userId, userId)), db.select().from(vaultForms).where(eq(vaultForms.userId, userId)), db.select().from(workspaceDatabases).where(eq(workspaceDatabases.userId, userId)), db.select().from(vaultItemStates).where(eq(vaultItemStates.userId, userId)),
    ]);
    const stateByKey = new Map(states.map((state) => [`${state.itemType}:${state.itemId}`, state]));
    const make = (type: z.infer<typeof itemTypeSchema>, row: any, nativeFavorite = false, nativeTrash: Date | null = null, href = "") => { const state = stateByKey.get(`${type}:${row.id}`); return { id: row.id, type, title: row.title ?? row.name, description: row.description ?? null, href, favorite: state?.favorite ?? nativeFavorite, trashedAt: state?.trashedAt ?? nativeTrash, lastOpenedAt: state?.lastOpenedAt ?? row.updatedAt ?? row.createdAt, updatedAt: row.updatedAt ?? row.createdAt }; };
    const items = [ ...docRows.map((r) => make("document", r, r.favorite, r.deletedAt, "/document-vault")), ...folderRows.map((r) => make("folder", r, r.favorite, r.deletedAt, "/document-vault")), ...sheetRows.map((r) => make("sheet", r, r.favorite, null, `/spreadsheets/${r.id}`)), ...canvasRows.map((r) => make("canvas", r, r.favorite, null, `/canvases/${r.id}`)), ...slideRows.map((r) => make("slide", r, r.favorite, r.deletedAt, `/slides/${r.id}`)), ...formRows.map((r) => make("form", r, r.favorite, r.deletedAt, `/forms/catalog/${r.id}`)), ...tableRows.map((r) => make("table", r, r.favorite, null, `/databases/${r.id}`)) ];
    const view = req.query.view === "favorites" || req.query.view === "trash" ? req.query.view : "recent";
    const filtered = items.filter((item) => view === "trash" ? Boolean(item.trashedAt) : !item.trashedAt && (view !== "favorites" || item.favorite)).sort((a, b) => +new Date(b.lastOpenedAt) - +new Date(a.lastOpenedAt));
    res.json({ items: filtered, view });
  });
  app.patch("/api/vault/items/:type/:id", isAuthenticated, async (req, res) => { try { const type = itemTypeSchema.parse(req.params.type); const id = parseId(req.params.id); if (!id) return res.status(400).json({ error: "Invalid item id." }); if (!await ownsItem(req.session.userId!, type, id)) return res.status(404).json({ error: "Vault item not found." }); const { action } = stateInputSchema.parse(req.body); const [current] = await db.select().from(vaultItemStates).where(and(eq(vaultItemStates.userId, req.session.userId!), eq(vaultItemStates.itemType, type), eq(vaultItemStates.itemId, id))).limit(1); if (action === "delete") { if (!current?.trashedAt) return res.status(409).json({ error: "Move an item to Trash before deleting it forever." }); await permanentlyDeleteItem(req.session.userId!, type, id); return res.json({ deleted: true }); } const state = action === "favorite" ? await upsertState(req.session.userId!, type, id, { favorite: !(current?.favorite ?? false) }) : action === "trash" ? await upsertState(req.session.userId!, type, id, { trashedAt: new Date() }) : action === "restore" ? await upsertState(req.session.userId!, type, id, { trashedAt: null }) : await upsertState(req.session.userId!, type, id, { lastOpenedAt: new Date() }); res.json({ state }); } catch (error) { res.status(400).json({ error: error instanceof z.ZodError ? error.flatten() : "Invalid vault action." }); } });
}

export { defaultSlideDocument };
