import { useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { CalendarDays, Check, Download, ListChecks, Plus, Repeat2, ShoppingBasket, Trash2 } from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { getLocalDateString } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Food = { id: number; name: string; servingSizeGrams: number };
type Recipe = { id: number; name: string; servings: number };
type PlanEntry = { id: number; scheduledDate: string; mealSlot: string; foodId: number | null; recipeId: number | null; foodName: string | null; recipeName: string | null; quantity: number; inputUnit: "g" | "serving" | "recipe_serving"; status: "planned" | "logged" | "skipped" };
type MealPlan = { id: number; name: string; startDate: string; endDate: string; status: "active" | "archived"; note: string | null; entries: PlanEntry[] };
type PlanReport = { days: Array<{ date: string; plannedIntents: number; stillPlanned: number; confirmedPlanEntries: number; skippedPlanEntries: number; linkedDiaryRecords: number; otherDiaryRecords: number }>; totals: { plannedIntents: number; stillPlanned: number; confirmedPlanEntries: number; skippedPlanEntries: number; linkedDiaryRecords: number; otherDiaryRecords: number }; missingLinkedDiaryRecords: number; timeZone: string; disclosure: string };

function addDays(date: string, days: number): string { const value = new Date(`${date}T00:00:00.000Z`); value.setUTCDate(value.getUTCDate() + days); return value.toISOString().slice(0, 10); }
function addMonths(month: string, months: number): string { const value = new Date(`${month}-01T00:00:00.000Z`); value.setUTCMonth(value.getUTCMonth() + months); return value.toISOString().slice(0, 7); }
function monthCalendarDays(month: string): string[] { const first = `${month}-01`; const leading = new Date(`${first}T00:00:00.000Z`).getUTCDay(); return Array.from({ length: 42 }, (_, index) => addDays(first, index - leading)); }

export default function MealPlanner() {
  const initialDate = getLocalDateString();
  const [expanded, setExpanded] = useState(false);
  const [selectedPlanId, setSelectedPlanId] = useState("");
  const [name, setName] = useState("");
  const [startDate, setStartDate] = useState(initialDate);
  const [endDate, setEndDate] = useState(addDays(initialDate, 6));
  const [sourceType, setSourceType] = useState<"food" | "recipe">("food");
  const [sourceId, setSourceId] = useState("");
  const [scheduledDate, setScheduledDate] = useState(initialDate);
  const [mealSlot, setMealSlot] = useState("other");
  const [calendarMonth, setCalendarMonth] = useState(initialDate.slice(0, 7));
  const [quantity, setQuantity] = useState("1");
  const [inputUnit, setInputUnit] = useState<"g" | "serving" | "recipe_serving">("serving");
  const plans = useQuery<{ plans: MealPlan[]; disclosure: string }>({ queryKey: ["/api/nutrition/meal-plans"], queryFn: () => apiRequest("/api/nutrition/meal-plans") });
  const foods = useQuery<{ foods: Food[] }>({ queryKey: ["/api/nutrition/foods"], queryFn: () => apiRequest("/api/nutrition/foods") });
  const recipes = useQuery<{ recipes: Recipe[] }>({ queryKey: ["/api/nutrition/recipes"], queryFn: () => apiRequest("/api/nutrition/recipes") });
  const selectedPlan = useMemo(() => plans.data?.plans.find((plan) => plan.id === Number(selectedPlanId)), [plans.data, selectedPlanId]);
  const planStatus = useMemo(() => ({
    planned: selectedPlan?.entries.filter((entry) => entry.status === "planned").length || 0,
    logged: selectedPlan?.entries.filter((entry) => entry.status === "logged").length || 0,
    skipped: selectedPlan?.entries.filter((entry) => entry.status === "skipped").length || 0,
  }), [selectedPlan]);
  const calendarDays = useMemo(() => monthCalendarDays(calendarMonth), [calendarMonth]);
  const entriesByDate = useMemo(() => {
    const result = new Map<string, PlanEntry[]>();
    for (const entry of selectedPlan?.entries || []) result.set(entry.scheduledDate, [...(result.get(entry.scheduledDate) || []), entry]);
    return result;
  }, [selectedPlan]);
  const grocery = useQuery<{ items: Array<{ foodId: number; foodName: string; totalGrams: number }>; disclosure: string }>({
    queryKey: ["/api/nutrition/meal-plans/grocery", { planId: selectedPlanId }],
    queryFn: () => apiRequest(`/api/nutrition/meal-plans/${selectedPlanId}/grocery`), enabled: Boolean(selectedPlanId),
  });
  const report = useQuery<PlanReport>({ queryKey: ["/api/nutrition/meal-plans/report", { planId: selectedPlanId }], queryFn: () => apiRequest(`/api/nutrition/meal-plans/${selectedPlanId}/report`), enabled: Boolean(selectedPlanId) });
  const refresh = () => Promise.all([
    queryClient.invalidateQueries({ queryKey: ["/api/nutrition/meal-plans"] }),
    queryClient.invalidateQueries({ queryKey: ["/api/nutrition/meal-plans/grocery"] }),
    queryClient.invalidateQueries({ queryKey: ["/api/nutrition/meal-plans/report"] }),
    queryClient.invalidateQueries({ queryKey: ["/api/nutrition/diary"] }),
    queryClient.invalidateQueries({ queryKey: ["/api/nutrition/trends"] }),
    queryClient.invalidateQueries({ queryKey: ["/api/nutrition/contributions"] }),
  ]);
  const createPlan = useMutation({
    mutationFn: () => apiRequest<{ plan: MealPlan }>("/api/nutrition/meal-plans", { method: "POST", body: JSON.stringify({ name, startDate, endDate }) }),
    onSuccess: ({ plan }) => { setName(""); setSelectedPlanId(String(plan.id)); setScheduledDate(plan.startDate); setCalendarMonth(plan.startDate.slice(0, 7)); void refresh(); },
  });
  const duplicatePlan = useMutation({
    mutationFn: (plan: MealPlan) => apiRequest<{ plan: MealPlan }>(`/api/nutrition/meal-plans/${plan.id}/duplicate`, { method: "POST", body: JSON.stringify({ name: `${plan.name} copy`, startDate: addDays(plan.endDate, 1) }) }),
    onSuccess: ({ plan }) => { setSelectedPlanId(String(plan.id)); setScheduledDate(plan.startDate); setCalendarMonth(plan.startDate.slice(0, 7)); void refresh(); },
  });
  const deletePlan = useMutation({ mutationFn: (id: number) => apiRequest(`/api/nutrition/meal-plans/${id}`, { method: "DELETE" }), onSuccess: () => { setSelectedPlanId(""); void refresh(); } });
  const archivePlan = useMutation({ mutationFn: (plan: MealPlan) => apiRequest(`/api/nutrition/meal-plans/${plan.id}/archive`, { method: "PATCH", body: JSON.stringify({ archived: plan.status !== "archived" }) }), onSuccess: () => void refresh() });
  const addEntry = useMutation({
    mutationFn: () => apiRequest(`/api/nutrition/meal-plans/${selectedPlanId}/entries`, { method: "POST", body: JSON.stringify({ scheduledDate, mealSlot, foodId: sourceType === "food" ? Number(sourceId) : null, recipeId: sourceType === "recipe" ? Number(sourceId) : null, quantity: Number(quantity), inputUnit }) }),
    onSuccess: () => { setSourceId(""); setQuantity("1"); void refresh(); },
  });
  const removeEntry = useMutation({ mutationFn: (id: number) => apiRequest(`/api/nutrition/meal-plan-entries/${id}`, { method: "DELETE" }), onSuccess: () => void refresh() });
  const setEntryStatus = useMutation({ mutationFn: ({ id, status }: { id: number; status: "planned" | "skipped" }) => apiRequest(`/api/nutrition/meal-plan-entries/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }), onSuccess: () => void refresh() });
  const logEntry = useMutation({ mutationFn: (id: number) => apiRequest(`/api/nutrition/meal-plan-entries/${id}/log`, { method: "POST" }), onSuccess: () => void refresh() });
  const invalidPlan = !name.trim() || !startDate || !endDate || endDate < startDate;
  const invalidEntry = !selectedPlan || !sourceId || !scheduledDate || Number(quantity) <= 0 || scheduledDate < selectedPlan.startDate || scheduledDate > selectedPlan.endDate;
  const firstPlanMonth = selectedPlan?.startDate.slice(0, 7) || calendarMonth;
  const lastPlanMonth = selectedPlan?.endDate.slice(0, 7) || calendarMonth;
  const downloadGrocery = () => {
    if (!grocery.data?.items.length || !selectedPlan) return;
    const quote = (value: string | number) => `"${String(value).replaceAll('"', '""')}"`;
    const csv = ["Food,Total grams", ...grocery.data.items.map((item) => `${quote(item.foodName)},${item.totalGrams}`)].join("\r\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${selectedPlan.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "meal-plan"}-preparation.csv`; anchor.click();
    URL.revokeObjectURL(url);
  };
  const downloadReport = () => {
    if (!report.data || !selectedPlan) return;
    const csv = ["Date,Planned intents,Still planned,Confirmed plan entries,Skipped plan entries,Linked diary food records,Other diary food records", ...report.data.days.map((day) => [day.date, day.plannedIntents, day.stillPlanned, day.confirmedPlanEntries, day.skippedPlanEntries, day.linkedDiaryRecords, day.otherDiaryRecords].join(","))].join("\r\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${selectedPlan.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "meal-plan"}-plan-vs-diary.csv`; anchor.click(); URL.revokeObjectURL(url);
  };

  return <section className="glassmorphic rounded-2xl p-6 mb-8 border border-primary/30" aria-labelledby="meal-planner-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="meal-planner-heading" className="font-orbitron text-lg text-primary flex items-center gap-2"><CalendarDays className="h-5 w-5" />Meal planning</h2><p className="mt-1 text-sm text-muted-foreground">Plan meals privately, derive preparation quantities, then explicitly confirm anything you actually ate.</p></div><Button variant="outline" size="sm" onClick={() => setExpanded((value) => !value)}>{expanded ? "Close planner" : "Plan meals"}</Button></div>
    {expanded ? <div className="mt-5 grid gap-4 lg:grid-cols-2">
      <div className="rounded-xl border border-primary/15 bg-background/25 p-4"><h3 className="text-sm font-semibold">Create a date-bounded plan</h3><div className="mt-3 grid gap-2 sm:grid-cols-2"><Input aria-label="Meal plan name" className="sm:col-span-2" placeholder="Plan name" value={name} onChange={(event) => setName(event.target.value)} /><label className="text-xs text-muted-foreground">Starts<Input className="mt-1" type="date" value={startDate} onChange={(event) => { setStartDate(event.target.value); if (endDate < event.target.value) setEndDate(event.target.value); }} /></label><label className="text-xs text-muted-foreground">Ends<Input className="mt-1" type="date" min={startDate} value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label><Button className="sm:col-span-2" variant="outline" disabled={invalidPlan || createPlan.isPending} onClick={() => createPlan.mutate()}><Plus />Create plan</Button></div></div>
      <div className="rounded-xl border border-primary/15 bg-background/25 p-4"><h3 className="text-sm font-semibold">Current plan</h3><div className="mt-3 flex flex-wrap gap-2"><select aria-label="Meal plan" className="h-10 min-w-0 flex-1 rounded-md border border-input bg-background px-3 text-sm" value={selectedPlanId} onChange={(event) => { setSelectedPlanId(event.target.value); const plan = plans.data?.plans.find((item) => item.id === Number(event.target.value)); if (plan) { setScheduledDate(plan.startDate); setCalendarMonth(plan.startDate.slice(0, 7)); } }}><option value="">Choose a plan</option>{plans.data?.plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} · {plan.startDate}–{plan.endDate}{plan.status === "archived" ? " · archived" : ""}</option>)}</select>{selectedPlan ? <><Button variant="ghost" size="sm" disabled={duplicatePlan.isPending} onClick={() => duplicatePlan.mutate(selectedPlan)}><Repeat2 />Duplicate next</Button><Button variant="ghost" size="sm" onClick={() => archivePlan.mutate(selectedPlan)}>{selectedPlan.status === "archived" ? "Restore" : "Archive"}</Button><Button variant="ghost" size="icon" aria-label="Delete meal plan" disabled={deletePlan.isPending} onClick={() => deletePlan.mutate(selectedPlan.id)}><Trash2 className="h-4 w-4" /></Button></> : null}</div>{selectedPlan ? <p className="mt-2 text-[11px] text-muted-foreground">Duplicate next copies this plan into the immediately following date range as planned intent; it never copies diary evidence.</p> : null}{plans.data?.disclosure ? <p className="mt-2 text-xs text-muted-foreground">{plans.data.disclosure}</p> : null}</div>
      {selectedPlan ? <div className="rounded-xl border border-primary/15 bg-background/25 p-4 lg:col-span-2"><h3 className="text-sm font-semibold flex items-center gap-2"><Plus className="h-4 w-4 text-primary" />Add a planned meal</h3><div className="mt-3 grid gap-2 sm:grid-cols-6"><select aria-label="Planned source type" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={sourceType} onChange={(event) => { const type = event.target.value as "food" | "recipe"; setSourceType(type); setSourceId(""); setInputUnit(type === "recipe" ? "recipe_serving" : "serving"); }}><option value="food">Food</option><option value="recipe">Saved meal</option></select><select aria-label="Planned food or recipe" className="h-10 rounded-md border border-input bg-background px-3 text-sm sm:col-span-2" value={sourceId} onChange={(event) => setSourceId(event.target.value)}><option value="">Choose {sourceType}</option>{(sourceType === "food" ? foods.data?.foods : recipes.data?.recipes)?.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input aria-label="Planned quantity" type="number" min="0.01" step="0.01" value={quantity} onChange={(event) => setQuantity(event.target.value)} /><select aria-label="Planned quantity unit" disabled={sourceType === "recipe"} className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={inputUnit} onChange={(event) => setInputUnit(event.target.value as "g" | "serving" | "recipe_serving")}><option value={sourceType === "recipe" ? "recipe_serving" : "serving"}>{sourceType === "recipe" ? "recipe servings" : "servings"}</option>{sourceType === "food" ? <option value="g">grams</option> : null}</select><select aria-label="Planned meal slot" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={mealSlot} onChange={(event) => setMealSlot(event.target.value)}>{["breakfast", "lunch", "dinner", "snack", "other"].map((slot) => <option key={slot} value={slot}>{slot}</option>)}</select><Input aria-label="Planned meal date" className="sm:col-span-2" type="date" min={selectedPlan.startDate} max={selectedPlan.endDate} value={scheduledDate} onChange={(event) => setScheduledDate(event.target.value)} /><Button className="sm:col-span-2" variant="outline" disabled={invalidEntry || addEntry.isPending} onClick={() => addEntry.mutate()}><Plus />Add planned meal</Button></div></div> : null}
      {selectedPlan ? <div className="rounded-xl border border-primary/15 bg-background/25 p-4 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold flex items-center gap-2"><CalendarDays className="h-4 w-4 text-primary" />Plan calendar</h3><p className="mt-1 text-[11px] text-muted-foreground">Select an in-range day to use it in the planned-meal form. Status colors describe records only.</p></div><div className="flex items-center gap-1"><Button size="sm" variant="ghost" disabled={calendarMonth <= firstPlanMonth} onClick={() => setCalendarMonth(addMonths(calendarMonth, -1))}>Previous</Button><span className="min-w-28 text-center text-xs font-semibold">{new Intl.DateTimeFormat(undefined, { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${calendarMonth}-01T00:00:00.000Z`))}</span><Button size="sm" variant="ghost" disabled={calendarMonth >= lastPlanMonth} onClick={() => setCalendarMonth(addMonths(calendarMonth, 1))}>Next</Button></div></div><div className="mt-3 grid grid-cols-7 gap-1" role="grid" aria-label={`${selectedPlan.name} meal plan calendar`}>{["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => <div key={day} role="columnheader" className="px-1 py-1 text-center text-[10px] uppercase tracking-wide text-muted-foreground">{day}</div>)}{calendarDays.map((date) => { const dayEntries = entriesByDate.get(date) || []; const inMonth = date.slice(0, 7) === calendarMonth; const inPlan = date >= selectedPlan.startDate && date <= selectedPlan.endDate; const counts = { planned: dayEntries.filter((entry) => entry.status === "planned").length, logged: dayEntries.filter((entry) => entry.status === "logged").length, skipped: dayEntries.filter((entry) => entry.status === "skipped").length }; return <button key={date} type="button" role="gridcell" disabled={!inPlan} aria-label={`${date}. ${counts.planned} planned, ${counts.logged} confirmed, ${counts.skipped} skipped`} aria-selected={scheduledDate === date} onClick={() => setScheduledDate(date)} className={`min-h-20 rounded-md border p-1 text-left align-top transition-colors ${scheduledDate === date ? "border-primary bg-primary/10" : "border-muted/15 bg-background/20"} ${!inMonth ? "opacity-35" : ""} ${!inPlan ? "cursor-default opacity-25" : "hover:border-primary/50"}`}><span className="text-[10px] text-muted-foreground">{Number(date.slice(8))}</span><span className="mt-1 block space-y-0.5 text-[10px] leading-tight">{counts.planned ? <span className="block rounded bg-amber-500/15 px-1 text-amber-200">{counts.planned} planned</span> : null}{counts.logged ? <span className="block rounded bg-emerald-500/15 px-1 text-emerald-200">{counts.logged} confirmed</span> : null}{counts.skipped ? <span className="block rounded bg-muted/20 px-1 text-muted-foreground">{counts.skipped} skipped</span> : null}</span></button>; })}</div></div> : null}
      {selectedPlan?.entries.length ? <div className="rounded-xl border border-primary/15 bg-background/25 p-4 lg:col-span-2"><h3 className="text-sm font-semibold flex items-center gap-2"><ListChecks className="h-4 w-4 text-primary" />Planned meals</h3><div className="mt-2 flex flex-wrap gap-2 text-xs text-muted-foreground" aria-label="Meal plan status summary"><span className="rounded-md border border-muted/20 px-2 py-1">Still planned: {planStatus.planned}</span><span className="rounded-md border border-muted/20 px-2 py-1">Confirmed into diary: {planStatus.logged}</span><span className="rounded-md border border-muted/20 px-2 py-1">Marked skipped: {planStatus.skipped}</span></div><p className="mt-2 text-[11px] text-muted-foreground">This summarizes your plan decisions, not nutrition adherence or health performance.</p><div className="mt-3 space-y-2">{selectedPlan.entries.map((entry) => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-muted/20 px-3 py-2 text-sm"><div><p>{entry.foodName || entry.recipeName} <span className="text-muted-foreground">· {entry.quantity} {entry.inputUnit.replace("_", " ")} · {entry.mealSlot}</span></p><p className="text-xs text-muted-foreground">{entry.scheduledDate} · {entry.status}</p></div><div className="flex flex-wrap gap-1">{entry.status === "planned" ? <><Button size="sm" disabled={logEntry.isPending} onClick={() => logEntry.mutate(entry.id)}><Check />Log meal</Button><Button size="sm" variant="ghost" onClick={() => setEntryStatus.mutate({ id: entry.id, status: "skipped" })}>Skip</Button><Button size="icon" variant="ghost" aria-label="Delete planned meal" onClick={() => removeEntry.mutate(entry.id)}><Trash2 className="h-4 w-4" /></Button></> : entry.status === "skipped" ? <Button size="sm" variant="ghost" onClick={() => setEntryStatus.mutate({ id: entry.id, status: "planned" })}><Repeat2 />Restore plan</Button> : <span className="inline-flex items-center gap-1 text-xs text-primary"><Check className="h-3 w-3" />Logged as diary evidence</span>}</div></div>)}</div></div> : null}
      {selectedPlan && report.data ? <div className="rounded-xl border border-primary/15 bg-background/25 p-4 lg:col-span-2"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-semibold flex items-center gap-2"><ListChecks className="h-4 w-4 text-primary" />Plan versus diary</h3><p className="mt-1 text-[11px] text-muted-foreground">Calendar dates use {report.data.timeZone}. Counts stay factual and neutral.</p></div><Button size="sm" variant="ghost" onClick={downloadReport}><Download />Export report CSV</Button></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-xs"><thead><tr className="text-muted-foreground"><th className="py-1 pr-3">Date</th><th className="py-1 pr-3">Intent</th><th className="py-1 pr-3">Planned</th><th className="py-1 pr-3">Confirmed</th><th className="py-1 pr-3">Skipped</th><th className="py-1 pr-3">Linked diary records</th><th className="py-1">Other diary records</th></tr></thead><tbody>{report.data.days.map((day) => <tr key={day.date} className="border-t border-muted/15"><td className="py-1 pr-3">{day.date}</td><td className="py-1 pr-3">{day.plannedIntents}</td><td className="py-1 pr-3">{day.stillPlanned}</td><td className="py-1 pr-3">{day.confirmedPlanEntries}</td><td className="py-1 pr-3">{day.skippedPlanEntries}</td><td className="py-1 pr-3">{day.linkedDiaryRecords}</td><td className="py-1">{day.otherDiaryRecords}</td></tr>)}</tbody></table></div>{report.data.missingLinkedDiaryRecords ? <p className="mt-2 text-xs text-destructive" role="status">{report.data.missingLinkedDiaryRecords} linked diary record(s) are no longer present. Review your diary corrections.</p> : null}<p className="mt-2 text-[11px] text-muted-foreground">{report.data.disclosure}</p></div> : null}
      {selectedPlan ? <div className="rounded-xl border border-primary/15 bg-background/25 p-4 lg:col-span-2"><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold flex items-center gap-2"><ShoppingBasket className="h-4 w-4 text-primary" />Preparation list</h3><Button size="sm" variant="ghost" disabled={!grocery.data?.items.length} onClick={downloadGrocery}><Download />Export CSV</Button></div>{grocery.data?.items.length ? <div className="mt-3 grid gap-2 sm:grid-cols-2">{grocery.data.items.map((item) => <div key={item.foodId} className="flex justify-between rounded-md border border-muted/20 px-3 py-2 text-sm"><span>{item.foodName}</span><span className="font-mono text-primary">{item.totalGrams} g</span></div>)}</div> : <p className="mt-2 text-xs text-muted-foreground">No unlogged planned ingredients yet.</p>}<p className="mt-2 text-xs text-muted-foreground">{grocery.data?.disclosure}</p></div> : null}
      {(createPlan.error || addEntry.error || logEntry.error) ? <p className="text-xs text-destructive lg:col-span-2">Could not save that plan change. Check its dates, source, and quantity and try again.</p> : null}
    </div> : null}
  </section>;
}
