import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { CalendarCheck, Pencil, Plus, Trash2, X } from "lucide-react";
import { apiRequest, queryClient } from "@/lib/queryClient";
import { getLocalDateString } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type ProductIdentity = { brand: string | null; manufacturer: string | null; form: string | null; barcode: string | null; lotNumber: string | null; expiresOn: string | null };
type ScheduleEvent = { id: number; date: string; status: "taken" | "skipped"; supplementEntryId: number | null; nameSnapshot: string; amountSnapshot: number | null; unitSnapshot: string | null; timeOfDaySnapshot: string | null; brandSnapshot: string | null; manufacturerSnapshot: string | null; formSnapshot: string | null; barcodeSnapshot: string | null; lotNumberSnapshot: string | null; expiresOnSnapshot: string | null; note: string | null };
type Schedule = ProductIdentity & { id: number; name: string; amount: number | null; unit: string | null; cadence: "daily" | "specific_days" | "as_needed"; weekdays: number[]; timeOfDay: string | null; reminderEnabled: boolean; active: boolean; note: string | null; due: boolean; event: ScheduleEvent | null };
const weekdayLabels = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

export default function SupplementSchedules() {
  const [date, setDate] = useState(getLocalDateString());
  const [editingId, setEditingId] = useState<number | null>(null);
  const [name, setName] = useState("");
  const [amount, setAmount] = useState("");
  const [unit, setUnit] = useState("mg");
  const [brand, setBrand] = useState("");
  const [manufacturer, setManufacturer] = useState("");
  const [form, setForm] = useState("");
  const [barcode, setBarcode] = useState("");
  const [lotNumber, setLotNumber] = useState("");
  const [expiresOn, setExpiresOn] = useState("");
  const [cadence, setCadence] = useState<Schedule["cadence"]>("daily");
  const [weekdays, setWeekdays] = useState<number[]>([]);
  const [timeOfDay, setTimeOfDay] = useState("");
  const [active, setActive] = useState(true);
  const [reminderEnabled, setReminderEnabled] = useState(false);
  const [note, setNote] = useState("");
  const [eventNote, setEventNote] = useState("");
  const [historyDays, setHistoryDays] = useState(30);
  const schedules = useQuery<{ schedules: Schedule[]; disclosure: string }>({ queryKey: ["/api/supplement-schedules", { date }], queryFn: () => apiRequest(`/api/supplement-schedules?date=${date}`) });
  const history = useQuery<{ events: ScheduleEvent[]; days: number; disclosure: string }>({ queryKey: ["/api/supplement-schedules/history", { historyDays }], queryFn: () => apiRequest(`/api/supplement-schedules/history?days=${historyDays}`) });
  const reset = () => { setEditingId(null); setName(""); setAmount(""); setUnit("mg"); setBrand(""); setManufacturer(""); setForm(""); setBarcode(""); setLotNumber(""); setExpiresOn(""); setCadence("daily"); setWeekdays([]); setTimeOfDay(""); setReminderEnabled(false); setActive(true); setNote(""); };
  const save = useMutation({ mutationFn: () => apiRequest(editingId ? `/api/supplement-schedules/${editingId}` : "/api/supplement-schedules", { method: editingId ? "PATCH" : "POST", body: JSON.stringify({ name, amount: amount ? Number(amount) : null, unit: amount ? unit : null, brand: brand.trim() || null, manufacturer: manufacturer.trim() || null, form: form.trim() || null, barcode: barcode.trim() || null, lotNumber: lotNumber.trim() || null, expiresOn: expiresOn || null, cadence, weekdays: cadence === "specific_days" ? weekdays : [], timeOfDay: timeOfDay || null, reminderEnabled, active, note: note.trim() || null }) }), onSuccess: () => { reset(); void queryClient.invalidateQueries({ queryKey: ["/api/supplement-schedules"] }); } });
  const remove = useMutation({ mutationFn: (id: number) => apiRequest(`/api/supplement-schedules/${id}`, { method: "DELETE" }), onSuccess: () => { reset(); void queryClient.invalidateQueries({ queryKey: ["/api/supplement-schedules"] }); } });
  const recordEvent = useMutation({ mutationFn: ({ id, status }: { id: number; status: "taken" | "skipped" }) => apiRequest(`/api/supplement-schedules/${id}/event`, { method: "PUT", body: JSON.stringify({ date, status, note: eventNote.trim() || null }) }), onSuccess: () => { setEventNote(""); void queryClient.invalidateQueries({ queryKey: ["/api/supplement-schedules"] }); void queryClient.invalidateQueries({ queryKey: ["/api/supplement-schedules/history"] }); void queryClient.invalidateQueries({ queryKey: ["/api/health-fitness/supplements"] }); } });
  const clearEvent = useMutation({ mutationFn: (id: number) => apiRequest(`/api/supplement-schedules/${id}/event/${date}`, { method: "DELETE" }), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["/api/supplement-schedules"] }); void queryClient.invalidateQueries({ queryKey: ["/api/health-fitness/supplements"] }); } });
  const edit = (schedule: Schedule) => { setEditingId(schedule.id); setName(schedule.name); setAmount(schedule.amount == null ? "" : String(schedule.amount)); setUnit(schedule.unit || "mg"); setBrand(schedule.brand || ""); setManufacturer(schedule.manufacturer || ""); setForm(schedule.form || ""); setBarcode(schedule.barcode || ""); setLotNumber(schedule.lotNumber || ""); setExpiresOn(schedule.expiresOn || ""); setCadence(schedule.cadence); setWeekdays(schedule.weekdays); setTimeOfDay(schedule.timeOfDay || ""); setReminderEnabled(schedule.reminderEnabled); setActive(schedule.active); setNote(schedule.note || ""); };

  return <section className="glassmorphic rounded-2xl p-6 mb-8 border border-primary/30" aria-labelledby="supplement-schedules-heading">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="supplement-schedules-heading" className="font-orbitron text-lg text-primary flex items-center gap-2"><CalendarCheck className="h-5 w-5" />Supplement schedules</h2><p className="mt-1 text-sm text-muted-foreground">Track your own schedule and factual taken/skipped state. This is not product, dose, timing, or treatment advice.</p></div><Input className="h-8 w-36 text-xs" aria-label="Supplement schedule date" type="date" value={date} onChange={(event) => setDate(event.target.value)} /></div>
    <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_7rem_6rem_10rem_9rem_auto]"><Input aria-label="Scheduled supplement name" placeholder="Name" value={name} onChange={(event) => setName(event.target.value)} /><Input aria-label="Scheduled supplement amount" type="number" min="0" step="0.01" placeholder="Amount" value={amount} onChange={(event) => setAmount(event.target.value)} /><Input aria-label="Scheduled supplement unit" placeholder="Unit" value={unit} onChange={(event) => setUnit(event.target.value)} /><select aria-label="Supplement schedule cadence" className="h-10 rounded-md border border-input bg-background px-3 text-sm" value={cadence} onChange={(event) => setCadence(event.target.value as Schedule["cadence"])}><option value="daily">Daily</option><option value="specific_days">Specific days</option><option value="as_needed">As needed</option></select><Input aria-label="Supplement schedule time" type="time" value={timeOfDay} onChange={(event) => setTimeOfDay(event.target.value)} /><Button size="sm" disabled={!name.trim() || (amount !== "" && (!Number(amount) || !unit.trim())) || (cadence === "specific_days" && !weekdays.length) || save.isPending} onClick={() => save.mutate()}>{editingId ? <Pencil /> : <Plus />}{editingId ? "Update" : "Add"}</Button></div>
    <details className="mt-2 rounded-lg border border-muted/20 p-3"><summary className="cursor-pointer text-xs text-muted-foreground">Optional product and lot details</summary><p className="mt-1 text-[11px] text-muted-foreground">Record label facts only. LyfeOS does not verify a product or interpret expiry, safety, efficacy, or interactions.</p><div className="mt-2 grid gap-2 sm:grid-cols-3"><Input aria-label="Supplement brand" placeholder="Brand" value={brand} onChange={(event) => setBrand(event.target.value)} /><Input aria-label="Supplement manufacturer" placeholder="Manufacturer" value={manufacturer} onChange={(event) => setManufacturer(event.target.value)} /><Input aria-label="Supplement form" placeholder="Form, e.g. capsule" value={form} onChange={(event) => setForm(event.target.value)} /><Input aria-label="Supplement barcode" placeholder="Barcode" value={barcode} onChange={(event) => setBarcode(event.target.value)} /><Input aria-label="Supplement lot number" placeholder="Lot number" value={lotNumber} onChange={(event) => setLotNumber(event.target.value)} /><Input aria-label="Supplement expiration date" type="date" value={expiresOn} onChange={(event) => setExpiresOn(event.target.value)} /></div></details>
    {cadence === "specific_days" ? <div className="mt-2 flex flex-wrap gap-2" aria-label="Supplement schedule weekdays">{weekdayLabels.map((label, day) => <label key={label} className="flex items-center gap-1 text-xs text-muted-foreground"><input type="checkbox" checked={weekdays.includes(day)} onChange={() => setWeekdays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day])} />{label}</label>)}</div> : null}
    <div className="mt-2 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><Input aria-label="Supplement schedule note" placeholder="Optional personal context" value={note} onChange={(event) => setNote(event.target.value)} /><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={reminderEnabled} onChange={(event) => setReminderEnabled(event.target.checked)} />Show in-app due cue</label><label className="flex items-center gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={active} onChange={(event) => setActive(event.target.checked)} />Active</label></div>
    <Input className="mt-2" aria-label="Supplement event note" placeholder="Optional note for the next taken/skipped record" value={eventNote} onChange={(event) => setEventNote(event.target.value)} />
    {editingId ? <Button className="mt-2" variant="ghost" size="sm" onClick={reset}>Cancel edit</Button> : null}
    {save.error ? <p className="mt-2 text-xs text-destructive">Could not save that schedule. Check the amount, unit, and selected days.</p> : null}
    {schedules.data?.schedules.length ? <div className="mt-4 space-y-2">{schedules.data.schedules.map((schedule) => <div key={schedule.id} className={`rounded-lg border border-muted/20 bg-background/20 p-3 text-xs ${schedule.active ? "" : "opacity-60"}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{schedule.name}{schedule.amount != null ? ` · ${schedule.amount} ${schedule.unit || ""}` : ""}</p><p className="mt-1 text-muted-foreground">{schedule.cadence === "specific_days" ? schedule.weekdays.map((day) => weekdayLabels[day]).join(", ") : schedule.cadence.replace("_", " ")}{schedule.timeOfDay ? ` · ${schedule.timeOfDay}` : ""}{schedule.note ? ` · ${schedule.note}` : ""}</p></div><span className="font-mono uppercase text-muted-foreground">{schedule.event?.status || (schedule.due ? "due" : schedule.active ? "not scheduled" : "inactive")}</span></div><div className="mt-2 flex flex-wrap gap-1">{schedule.active ? <Button variant="outline" size="sm" disabled={recordEvent.isPending} onClick={() => recordEvent.mutate({ id: schedule.id, status: "taken" })}>Taken</Button> : null}{schedule.active && schedule.cadence !== "as_needed" ? <Button variant="ghost" size="sm" disabled={recordEvent.isPending} onClick={() => recordEvent.mutate({ id: schedule.id, status: "skipped" })}>Skipped</Button> : null}{schedule.event ? <Button variant="ghost" size="sm" disabled={clearEvent.isPending} onClick={() => clearEvent.mutate(schedule.id)}><X />Clear state</Button> : null}<Button variant="ghost" size="icon" aria-label={`Edit ${schedule.name} schedule`} onClick={() => edit(schedule)}><Pencil className="h-4 w-4" /></Button><Button variant="ghost" size="icon" aria-label={`Delete ${schedule.name} schedule`} disabled={remove.isPending} onClick={() => remove.mutate(schedule.id)}><Trash2 className="h-4 w-4" /></Button></div></div>)}</div> : <p className="mt-4 text-xs text-muted-foreground">No supplement schedules yet.</p>}
    {schedules.data?.schedules.some((schedule) => schedule.brand || schedule.manufacturer || schedule.form || schedule.barcode || schedule.lotNumber || schedule.expiresOn) ? <details className="mt-3 rounded-lg border border-muted/20 p-3"><summary className="cursor-pointer text-xs font-medium text-muted-foreground">Recorded product and lot details</summary><div className="mt-2 space-y-1">{schedules.data.schedules.filter((schedule) => schedule.brand || schedule.manufacturer || schedule.form || schedule.barcode || schedule.lotNumber || schedule.expiresOn).map((schedule) => <p className="text-xs text-muted-foreground" key={schedule.id}>{schedule.name}{schedule.brand ? ` · ${schedule.brand}` : ""}{schedule.manufacturer ? ` · ${schedule.manufacturer}` : ""}{schedule.form ? ` · ${schedule.form}` : ""}{schedule.barcode ? ` · barcode ${schedule.barcode}` : ""}{schedule.lotNumber ? ` · lot ${schedule.lotNumber}` : ""}{schedule.expiresOn ? ` · label expiry ${schedule.expiresOn}` : ""}</p>)}</div></details> : null}
    <details className="mt-4 rounded-lg border border-muted/20 p-3"><summary className="cursor-pointer text-xs font-medium text-muted-foreground">Recorded schedule history ({history.data?.events.length || 0})</summary><div className="mt-2 flex justify-end"><select aria-label="Supplement schedule history period" className="h-8 rounded-md border border-input bg-background px-2 text-xs" value={historyDays} onChange={(event) => setHistoryDays(Number(event.target.value))}>{[30, 90, 365, 3650].map((days) => <option key={days} value={days}>{days === 3650 ? "10 years" : `${days} days`}</option>)}</select></div><div className="mt-2 space-y-1">{history.data?.events.map((event) => <p key={event.id} className="text-xs text-muted-foreground">{event.date} · {event.nameSnapshot}{event.amountSnapshot != null ? ` · ${event.amountSnapshot} ${event.unitSnapshot || ""}` : ""}{event.timeOfDaySnapshot ? ` · ${event.timeOfDaySnapshot}` : ""}{event.brandSnapshot ? ` · ${event.brandSnapshot}` : ""}{event.manufacturerSnapshot ? ` · ${event.manufacturerSnapshot}` : ""}{event.formSnapshot ? ` · ${event.formSnapshot}` : ""}{event.lotNumberSnapshot ? ` · lot ${event.lotNumberSnapshot}` : ""}{event.expiresOnSnapshot ? ` · label expiry ${event.expiresOnSnapshot}` : ""} · <span className="text-primary">{event.status}</span>{event.note ? ` · ${event.note}` : ""}</p>)}</div><p className="mt-2 text-[11px] text-muted-foreground">{history.data?.disclosure}</p></details>
    <p className="mt-4 text-[11px] text-muted-foreground">{schedules.data?.disclosure || "Schedules are user-authored records, not clinical guidance."} Due cues appear only inside LyfeOS; background delivery is not claimed.</p>
  </section>;
}
